parameters:
#    netgen_test.example.class: Netgen\Bundle\TestBundle\Example

services:
#    netgen_test.example:
#        class: %netgen_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
